const sidebars = {

    docs: [
        {
            type: 'category',
            label: 'product_overview',
            collapsible: true,
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'product_overview'
                }
            ],
        },
        {
            type: 'category',
            label: 'quick_start',
            collapsible: true,
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'quick_start'
                }
            ],
        },
        {
            type: 'category',
            label: 'system_install',
            collapsible: true,
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'system_install'
                }
            ],
        },
        {
            type: 'category',
            label: 'data_acquisition',
            collapsible: true,
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'data_acquisition'
                }
            ],
        },
        {
            type: 'category',
            label: 'data_processing',
            collapsible: true,
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'data_processing'
                }
            ],
        },
        {
            type: 'category',
            label: 'other',
            collapsible: true,
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'other'
                }
            ],
        },
        {
            type: 'category',
            label: 'operation_guide',
            collapsible: true,
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'operation_guide'
                }
            ],
        },
        {
            type: 'category',
            label: 'performance_testing',
            collapsible: true,
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'performance_testing'
                }
            ],
        },
        {
            type: 'category',
            label: 'faq',
            collapsible: true,
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'faq'
                }
            ],
        },
        {
            type: 'category',
            label: 'version_history',
            collapsible: true,
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'version_history'
                }
            ],
        }
    ],
};

module.exports = sidebars;
