const sidebars = {

    docs: [
        {
            type: 'category',
            label: 'developer_guid',
            collapsible: true,
            collapsed: true,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'developer_guid/docs'
                }
            ],
        }
    ],
};

module.exports = sidebars;
